#!/usr/bin/env bash
# Using while loop to display Best School 10 times,
# and on the 9th iteration, displays Best School and then Hi on a new line.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
