#!/usr/bin/env bash
# Using the for loop to display the contents of the current directory in list format.
#   Only displays the part of the name after the first dash is shown. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
